### ISSUE TITLE
Inserting a new Engagement via UI does not create Date Objects

### ISSUE THREAD

**Issue by devfoo-one** [devfoo-one/softwareprojekt-beuth#47]
StartDate and EndDate has to be something like a date-object like `ISODate("1914-07-14T22:00:00Z")`, but selecting a date via the DatePicker does only create a string `"2015/01/14"`

**Comment by devfoo-one** [comment]
Make shure that only Date objects i.e. `new Date(...)` are created

**Comment by robme91** [comment]
solved. check the pullrequest

**Comment by devfoo-one** [comment]
Please leave issues open until the corresponding PR is merged into master.
