### ISSUE TITLE
Rightsmanagement for engagements

### ISSUE THREAD

**Issue by robme91** [devfoo-one/softwareprojekt-beuth#49]
In publication.js enagments must be impl as the other collection, because engagements should also be shown only for the creators.

**Comment by devfoo-one** [comment]
I would wait with this. After talking to Daniel today i think that we may have to completely rewrite the whole engagements concept within the next sprint.

**Comment by robme91** [comment]
fixed

**Comment by devfoo-one** [comment]
Please leave issues open until the corresponding PR is merged into master.
