### ISSUE TITLE
Template Homepage is undefined

### ISSUE THREAD

**Issue by robme91** [devfoo-one/softwareprojekt-beuth#51]
if you open your project now on master branch there is a error in the console. 
TypeError: Template.Homepage is undefined
Template.Homepage.created = function() {

who did this? because i didn't find the homepage template or what it was nebfore. i didn't find the commit where that happened. we have to fix this quick

**Comment by devfoo-one** [comment]
can´t reproduce the error. But this line was added for E-Mail verification
https://devfoo-one@github.com/devfoo-one/softwareprojekt-beuth/blame/master/client/helpers/config.js#L17

**Comment by devfoo-one** [comment]
I can´t reproduce the error. But the line you are talking about was added for E-Mail verification.
https://github.com/devfoo-one/softwareprojekt-beuth/blame/master/client/helpers/config.js
There is no template called `homepage`, so i don´t know how to fix this right away. I can have a look at this tomorrow.

**Comment by robme91** [comment]
very strange if you haven't got the same error. if no one of the others got this, it must be my repo

**Comment by robme91** [comment]
now the navbar works again. but error is still there.

**Comment by devfoo-one** [comment]
Tell me the steps to reproduce the error.

**Comment by robme91** [comment]
i think the error just came on when you not loggedin and your are on the homepage. it's the first time i realize this error. maybe it's there a long time

**Comment by robme91** [comment]
no it'S not. error also come when I refresh signed in pages. a meteor reset didn't do anaything. very very strange. can't say how you can reproduce it. it was there after the i switched to master brange again from my last feature branch. i did a meteor reset to get the new changed fixtures and then the error was there. i'm interested if max or vici got the same

**Comment by frontsidekante** [comment]
I get the same error. "TypeError: Template.Homepage is undefined". 
I fucked that one up, there is in fact no Homepage template. No idea why Tom doesn't get that error.
I'll look into that.

**Comment by frontsidekante** [comment]
I changed "Homepage" to "dashboard". Works now.

**Comment by frontsidekante** [comment]
Nonononono. No. "dashboard" doesn't make any sense. I'll take care of that tomorrow. Sorry.

**Comment by Foaly** [comment]
What file are we talking about?

**Comment by frontsidekante** [comment]
config.js
