### ISSUE TITLE
After Sign Out route to Homepage

### ISSUE THREAD

**Issue by robme91** [devfoo-one/softwareprojekt-beuth#52]
If you sign out and you log in again with another user, you get on the same site like you loged out before. e.g. you are in the detail employee view on a specific employee then you log out and log in with another acc you get on the detail view again. you don't see anything because of god rights management but thats not a usefull behavior

**Comment by Foaly** [comment]
Take a look at this: http://stackoverflow.com/questions/14935747/user-sign-out-callback-in-meteor
