### ISSUE TITLE
Employee Timeline View [PMDASH-49]

### ISSUE THREAD

**Issue by devfoo-one** [devfoo-one/softwareprojekt-beuth#63]
I removed all the d3-gantt stuff and started a small html dummy for our employee timeline view. Take a look at 87ce21ab6050c628f1e04881f6ea198d6112644e [branch: dev_timelineViewV1_experimental](https://github.com/devfoo-one/softwareprojekt-beuth/tree/dev_timelineViewV1_experimental)
![staffingboard](https://cloud.githubusercontent.com/assets/5645199/7609092/d313afec-f96f-11e4-9167-4f9cfa086f61.jpg)

**Comment by Foaly** [comment]
looks nice! I will check it out later/tomorrow.

**Comment by devfoo-one** [comment]
Thanks. There´s absolutely no function yet, but i if i find time i´ll try to add more stuff. I think it would be a good idea to start with one view (4 weeks for example) ... cause zooming could get difficult.

**Comment by devfoo-one** [comment]
I´ll continue working on PMDASH-49 tomorrow.

**Comment by devfoo-one** [comment]
Frontend-Dev sucks! Here are 2 different solutions:
1. Divs with width
2. Stacked bootstrap progress bars
![staffingboard](https://cloud.githubusercontent.com/assets/5645199/7723661/9a03aa92-feea-11e4-87c0-ac0240570c05.jpg)
There is no Day-Grid because we need one large table-cell to place the progress-bars. If we want a grid we have to create some sort of "overlay" over the table or the cell.

**Comment by Foaly** [comment]
maybe we could get some help from one of the kreuzwerker frontend developers to decide whats best.

**Comment by Foaly** [comment]
maybe we could get some help from one of the kreuzwerker frontend developers to decide whats best.

**Comment by Foaly** [comment]
maybe we could get some help from one of the kreuzwerker frontend developers to decide whats best.

**Comment by devfoo-one** [comment]
- no grid needed
- month view is enough for next sprint
