### ISSUE TITLE
Make hours per week madatory

### ISSUE THREAD

**Issue by Foaly** [devfoo-one/softwareprojekt-beuth#77]
Also check that hpw is positiv and not 0

**Comment by devfoo-one** [comment]
within employees and assignments

**Comment by devfoo-one** [comment]
I added pattern checking for all inputs cee4f2cebab276a38093f7905c1370eee90ceee3 `pattern="\d{1,2}"` but this won´t check for zero like "0" ... could someone create a regex which also excludes "only-zeroes" ?
